

export const FETCH_ACTION = "FETCH_ACTION";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const GET_BLOCKS = "GET_BLOCKS";
export const SET_BLOCKS = "SET_BLOCKS";

export const API_ERROR = "API_ERROR";
export const SET_API_ERROR_MSG = "SET_API_ERROR_MSG"


export default { SET_API_ERROR_MSG, FETCH_ACTION, GET_TRANSACTIONS, SET_TRANSACTIONS, GET_BLOCKS, SET_BLOCKS, API_ERROR };